# LocalTax AI Assistant Configuration
# Replace with your actual credentials

# Email Configuration
imap:
  server: "imap.gmail.com"  # or your email provider's IMAP server
  port: 993
  username: "your-email@gmail.com"
  password: "your-app-password"  # Use app-specific password for Gmail
  ssl: true

# Progressive Training Configuration
training:
  mode: "hybrid"  # Options: "hybrid", "local_only", "training"
  online_dependency: 80  # Percentage (decreases over time as local knowledge grows)
  local_confidence_threshold: 0.85  # When to use local vs online knowledge

# OpenAI Configuration (for training phase)
openai:
  api_key: "your-openai-api-key"
  model: "gpt-4"
  max_tokens: 2000
  anonymization: true  # Always remove personal identifiers
  knowledge_caching: true  # Store responses locally

# Tax Year Configuration
tax_year: 2024

# File Processing
filters:
  date_range:
    start: "2024-01-01"
    end: "2024-12-31"
  keywords:
    - "invoice"
    - "receipt"
    - "rechnung"
    - "quittung"

# OCR Settings
ocr:
  language: "deu"  # German language for Tesseract
  confidence_threshold: 60

# WISO Integration
wiso:
  executable_path: ""  # Path to WISO software
  auto_fill: false  # Set to true for automatic filling
  supervision_mode: true  # User supervision required

# Mobile Capture Module
mobile:
  enabled: true
  sync_method: "cloud_folder"  # Options: "cloud_folder", "email", "disabled"
  cloud_folder_path: ""  # Path to your cloud sync folder (Google Drive, iCloud, etc.)
  mobile_email: ""  # Dedicated email for mobile uploads
  auto_sync_interval: 300  # Check for new images every 5 minutes
  image_formats: ["jpg", "jpeg", "png", "heic"]
  auto_delete_after_processing: false  # Keep originals in cloud

# Security
encryption:
  enabled: true
  method: "AES-256"
